font_size 26.0

adjust_line_height 10

font_family JetBrains Mono

enable_audio_bell no

cursor_shape block

shell_integration  no-cursor

allow_remote_control yes
map kitty_mod+h launch --stdin-source=@screen_scrollback --type=overlay /usr/bin/vim -R -M -c "set nospell syntax=" -c "vnoremap y :w !pbcopy<CR><CR>" -c "normal G" -c "nnoremap q :q!<CR>" -
